kind: Service
apiVersion: v1
metadata:
  name: mirror-webserver
  labels:
    app: mirror-webserver
spec:
  selector:
    app: mirror-webserver
  ports:
    - port: 8080
      name: http
  type: NodePort
---

kind: Deployment
apiVersion: apps/v1
metadata:
  name: mirror-webserver
  labels:
    app: mirror-webserver
spec:
  selector:                
    matchLabels:     
      app: mirror-webserver
  replicas: 1
  template:
    metadata:
      labels:
        app: mirror-webserver
        version: v1
    spec:
      containers:
      - name: mirror-webserver
        image: image-registry.openshift-image-registry.svc:5000/default/mirror-webserver:latest
        ports:
        - containerPort: 8080
      restartPolicy: Always
---