kind: Service
apiVersion: v1
metadata:
  name: test-webserver
  labels:
    app: test-webserver
spec:
  selector:
    app: test-webserver
  ports:
    - port: 8080
      name: http
  type: NodePort
---

kind: Deployment
apiVersion: apps/v1
metadata:
  name: test-webserver
  labels:
    app: test-webserver
spec:
  selector:                
    matchLabels:     
      app: test-webserver
  replicas: 1
  template:
    metadata:
      labels:
        app: test-webserver
        version: v1
    spec:
      containers:
      - name: test-webserver
        image: image-registry.openshift-image-registry.svc:5000/app-mod-dev/build-test-webserver:latest
        ports:
        - containerPort: 8080
      restartPolicy: Always
---